import './globals.css';
import { PanelProvider } from '@/lib/contexts/PanelContext';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import type { PropsWithChildren } from 'react';
import { QueryClientProvider } from '../components/providers/query-client-provider';
import { SolanaProvider } from '../components/providers/solana-provider';
import { getClientEnv } from '../lib/config/client-env';
// This will throw if env vars are missing
getClientEnv();

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <QueryClientProvider>
          <SolanaProvider>
            <PanelProvider>{children}</PanelProvider>
          </SolanaProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
