import {
  type Action,
  type ActionExample,
  type HandlerCallback,
  type IAgentRuntime,
  type Memory,
  type State,
  elizaLogger,
} from '@elizaos/core';

const GENERIC_REPLY_EXAMPLES: ActionExample[][] = [
  [
    {
      user: '{{user1}}',
      content: {
        text: 'Congrats on your launch! 🎉',
      },
    },
    {
      user: '{{user2}}',
      content: {
        text: 'Thank you so much! We appreciate your support!',
        action: 'GENERIC_REPLY',
      },
    },
  ],
  [
    {
      user: '{{user1}}',
      content: {
        text: 'Good luck with your project!',
      },
    },
    {
      user: '{{user2}}',
      content: {
        text: 'Thanks! Wishing you the best as well!',
        action: 'GENERIC_REPLY',
      },
    },
  ],
];

const GenericReplyAction: Action = {
  name: 'GENERIC_REPLY',
  similes: ['REPLY', 'THANK', 'ACKNOWLEDGE', 'RESPOND'],
  validate: async (_runtime: IAgentRuntime, _message: Memory) => true,
  description:
    'Send a simple, context-appropriate reply to generic tweets (greetings, congratulations, thanks, etc.)',
  handler: async (
    _runtime: IAgentRuntime,
    message: Memory,
    _initialState: State,
    _options: { [key: string]: unknown },
    callback?: HandlerCallback,
  ): Promise<boolean> => {
    elizaLogger.info('Handling GENERIC_REPLY action...');
    // For this action, just reply with a context-appropriate message (already generated by the model)
    if (callback) {
      callback({
        text: message.content.text,
        action: 'GENERIC_REPLY',
      });
    }
    return true;
  },
  examples: GENERIC_REPLY_EXAMPLES,
};

export default GenericReplyAction;
