CREATE TABLE IF NOT EXISTS spam_users (
  user_id TEXT PRIMARY KEY,
  spam_score FLOAT NOT NULL DEFAULT 0,
  last_tweet_date TIMESTAMP WITH TIME ZONE,
  tweet_count INTEGER NOT NULL DEFAULT 0,
  violations JSONB NOT NULL DEFAULT '[]',
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
); 