-- Add new columns for merged tweets
ALTER TABLE tweets
ADD COLUMN IF NOT EXISTS is_thread_merged BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS has_replies BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS thread_size INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS reply_count INTEGER DEFAULT 0; 