import type { TargetAccount } from '@/types/account';

export const mockAccounts: TargetAccount[] = [
  {
    userId: '1465903746408321026',
    username: 'naiivememe',
    displayName: 'naiive',
    description: 'Test account 1',
    followersCount: 1000,
    followingCount: 500,
    friendsCount: 400,
    mediaCount: 100,
    statusesCount: 1500,
    likesCount: 3000,
    listedCount: 10,
    tweetsCount: 1000,
    isPrivate: false,
    isVerified: false,
    isBlueVerified: false,
    joinedAt: new Date(),
    location: 'Test Location',
    avatarUrl: 'https://test.com/avatar.jpg',
    bannerUrl: 'https://test.com/banner.jpg',
    websiteUrl: 'https://test.com',
    canDm: true,
    createdAt: new Date(),
    lastUpdated: new Date(),
    isActive: true,
    source: 'twitter',
    avgLikes50: 100,
    avgRetweets50: 50,
    avgReplies50: 20,
    avgViews50: 1000,
    engagementRate50: 0.05,
    influenceScore: 0.8,
    last50TweetsUpdatedAt: new Date(),
  },
  {
    userId: '1351759713982050306',
    username: 'ChloeBailey',
    displayName: 'Chlöe',
    description: 'Test account 2',
    followersCount: 2000,
    followingCount: 1000,
    friendsCount: 800,
    mediaCount: 200,
    statusesCount: 3000,
    likesCount: 5000,
    listedCount: 20,
    tweetsCount: 2000,
    isPrivate: false,
    isVerified: false,
    isBlueVerified: false,
    joinedAt: new Date(),
    location: 'Test Location',
    avatarUrl: 'https://test.com/avatar2.jpg',
    bannerUrl: 'https://test.com/banner2.jpg',
    websiteUrl: 'https://test2.com',
    canDm: true,
    createdAt: new Date(),
    lastUpdated: new Date(),
    isActive: true,
    source: 'twitter',
    avgLikes50: 200,
    avgRetweets50: 100,
    avgReplies50: 40,
    avgViews50: 2000,
    engagementRate50: 0.08,
    influenceScore: 0.9,
    last50TweetsUpdatedAt: new Date(),
  },
];
