import type { Tweet } from 'agent-twitter-client';

// Crypto-related tweets
export const mockCryptoTweets: Tweet[] = [
  {
    bookmarkCount: 0,
    conversationId: '1906664825826001028',
    hashtags: [],
    html: '<a href="https://twitter.com/Favouritedotsui">@Favouritedotsui</a> <a href="https://twitter.com/WalrusProtocol">@WalrusProtocol</a> <a href="https://twitter.com/SuiNetwork">@SuiNetwork</a> <a href="https://twitter.com/SuiFoundation">@SuiFoundation</a> <a href="https://twitter.com/SuiFamOfficial">@SuiFamOfficial</a> 1 <a href="https://twitter.com/search?q=%24WAL">$WAL</a> = 1 <a href="https://twitter.com/search?q=%24APT">$APT</a>',
    id: '1906665176255885582',
    inReplyToStatus: undefined,
    inReplyToStatusId: '1906664825826001028',
    isQuoted: false,
    isPin: false,
    isReply: true,
    isRetweet: false,
    isSelfThread: false,
    likes: 11,
    name: 'matteodotsui',
    mentions: [
      { username: 'Favouritedotsui', id: '' },
      { username: 'WalrusProtocol', id: '' },
      { username: 'SuiNetwork', id: '' },
      { username: 'SuiFoundation', id: '' },
      { username: 'SuiFamOfficial', id: '' },
    ],
    permanentUrl: 'https://twitter.com/username/status/1906665176255885582',
    photos: [],
    place: undefined,
    quotedStatus: undefined,
    quotedStatusId: undefined,
    replies: 3,
    retweets: 1,
    retweetedStatus: undefined,
    retweetedStatusId: undefined,
    text: '@Favouritedotsui @WalrusProtocol @SuiNetwork @SuiFoundation @SuiFamOfficial 1 $WAL = 1 $APT',
    thread: [],
    timeParsed: new Date(),
    timestamp: Date.now(),
    urls: [],
    userId: 'test-user-1',
    username: 'matteodotsui',
    videos: [],
    views: 1000,
    sensitiveContent: false,
    poll: null,
  },
];

// Example of merged tweets (reply chain)
export const mockMergedTweets: Tweet[] = [
  {
    // Reply tweet
    id: '1906665176255885582',
    text: "[ORIGINAL POST] @Favouritedotsui: 'Which trade is your first for today? 👀 The chart is waiting.\n\nIf you sold your $WAL or did not stake DON'T TALK TO ME❄️\n\n@WalrusProtocol is ascending \n\n@matteodotsui predicts 1 $WAL = 1$  by Basecamp.\n\nWhat's your own prediction? https://t.co/6SROeyWVjw'>>>[REPLY] @matteodotsui: '@Favouritedotsui @WalrusProtocol @SuiNetwork @SuiFoundation @SuiFamOfficial 1 $WAL = 1 $APT'",
    userId: 'test-user-1',
    username: 'matteodotsui',
    name: 'matteodotsui',
    timestamp: Date.now(),
    timeParsed: new Date(),
    likes: 11,
    retweets: 1,
    replies: 3,
    views: 1000,
    bookmarkCount: 0,
    conversationId: '1906664825826001028',
    permanentUrl: 'https://twitter.com/username/status/1906665176255885582',
    html: '<a href="https://twitter.com/Favouritedotsui">@Favouritedotsui</a> <a href="https://twitter.com/WalrusProtocol">@WalrusProtocol</a> <a href="https://twitter.com/SuiNetwork">@SuiNetwork</a> <a href="https://twitter.com/SuiFoundation">@SuiFoundation</a> <a href="https://twitter.com/SuiFamOfficial">@SuiFamOfficial</a> 1 <a href="https://twitter.com/search?q=%24WAL">$WAL</a> = 1 <a href="https://twitter.com/search?q=%24APT">$APT</a>',
    inReplyToStatus: {
      id: '1906664825826001028',
      text: "Which trade is your first for today? 👀 The chart is waiting.\n\nIf you sold your $WAL or did not stake DON'T TALK TO ME❄️\n\n@WalrusProtocol is ascending \n\n@matteodotsui predicts 1 $WAL = 1$  by Basecamp.\n\nWhat's your own prediction?",
      userId: 'test-user-2',
      username: 'Favouritedotsui',
      timestamp: Date.now() - 1000, // 1 second earlier
      likes: 20,
      retweets: 5,
      replies: 10,
      hashtags: [],
      mentions: [
        { username: 'WalrusProtocol', id: '' },
        { username: 'matteodotsui', id: '' },
      ],
      photos: [],
      urls: [],
      videos: [],
      thread: [],
      timeParsed: new Date(Date.now() - 1000),
      permanentUrl: 'https://twitter.com/username/status/1906664825826001028',
      html: '',
      isQuoted: false,
      isPin: false,
      isReply: false,
      isRetweet: false,
      isSelfThread: false,
      sensitiveContent: false,
      bookmarkCount: 0,
      views: 2000,
      place: undefined,
      poll: null,
      inReplyToStatus: null,
      inReplyToStatusId: undefined,
      quotedStatus: null,
      quotedStatusId: undefined,
      retweetedStatus: null,
      retweetedStatusId: undefined,
      conversationId: '1906664825826001028',
      name: 'Favouritedotsui',
    },
    inReplyToStatusId: '1906664825826001028',
    quotedStatus: null,
    quotedStatusId: undefined,
    retweetedStatus: null,
    retweetedStatusId: undefined,
    thread: [],
    isQuoted: false,
    isPin: false,
    isReply: true,
    isRetweet: false,
    isSelfThread: false,
    sensitiveContent: false,
    hashtags: [],
    mentions: [
      { username: 'Favouritedotsui', id: '' },
      { username: 'WalrusProtocol', id: '' },
      { username: 'SuiNetwork', id: '' },
      { username: 'SuiFoundation', id: '' },
      { username: 'SuiFamOfficial', id: '' },
    ],
    photos: [],
    urls: [],
    videos: [],
    place: undefined,
    poll: null,
  },
];

// Combined mock tweets for testing
export const mockTweets: Tweet[] = [...mockCryptoTweets, ...mockMergedTweets];
