import type { Tweet, TweetWithUpstream } from '@/types/twitter';

// Crypto-related tweets
export const mockCryptoTweets: Tweet[] = [
  {
    bookmarkCount: 0,
    conversationId: '1904912364262015321',
    hashtags: [],
    html: '',
    id: '1904931680642634061',
    inReplyToStatus: undefined,
    inReplyToStatusId: '1904912364262015321',
    isQuoted: false,
    isPin: false,
    isReply: true,
    isRetweet: false,
    isSelfThread: false,
    likes: 11,
    name: 'Michal Nowak',
    mentions: [],
    permanentUrl: 'https://x.com/btc_seaside/status/1904931680642634061',
    photos: [],
    place: undefined,
    quotedStatus: undefined,
    quotedStatusId: undefined,
    replies: 3,
    retweets: 1,
    retweetedStatus: undefined,
    retweetedStatusId: undefined,
    text: 'joke?',
    thread: [],
    timeParsed: new Date(),
    timestamp: Date.now(),
    urls: [],
    userId: 'test-user-1',
    username: 'btc_seaside',
    videos: [],
    views: 1000,
    sensitiveContent: false,
    poll: null,
  },
];

// Example of merged tweets (reply chain)
export const mockMergedTweets: TweetWithUpstream[] = [
  {
    originalTweet: {
      id: 'ff158e75-e9a6-4a14-a0a9-151dadd3b0be',
      tweet_id: '1904931680642634061',
      agentId: 'b8af647b-f617-0ae3-ab07-acb81861d7e2',
      text: 'joke?',
      userId: 'test-user-1',
      username: 'btc_seaside',
      name: 'Michal Nowak',
      timestamp: 1744090480489,
      timeParsed: new Date('2025-04-08T05:34:40.489Z'),
      likes: 11,
      retweets: 1,
      replies: 3,
      views: 1000,
      bookmarkCount: 0,
      conversationId: '1904912364262015321',
      permanentUrl: 'https://x.com/btc_seaside/status/1904931680642634061',
      html: '',
      inReplyToStatusId: '1904912364262015321',
      threadSize: 4,
      isQuoted: false,
      isPin: false,
      isReply: true,
      isRetweet: false,
      isSelfThread: false,
      sensitiveContent: false,
      isThreadMerged: true,
      hashtags: [],
      mentions: [],
      photos: [],
      urls: [],
      videos: [],
      poll: null,
      mediaType: 'text',
      status: 'pending',
      createdAt: new Date('2025-04-08T05:34:41.039Z'),
      originalText: 'joke?',
      thread: [],
      homeTimeline: {
        publicMetrics: {
          likes: 11,
          retweets: 1,
          replies: 3,
        },
        entities: {
          hashtags: [],
          mentions: [],
          urls: [],
        },
      },
    },
    upstreamTweets: {
      inReplyChain: [
        {
          id: '9ed3b04a-35e1-4e3a-9d6b-7b90908536b3',
          tweet_id: '1904912364262015321',
          text: '@myAlphaDrops @Bybit_Official @use_corn 8 billion',
          username: 'x256xx',
          status: 'pending',
          createdAt: new Date('2025-04-08T05:34:41.039Z'),
          isThreadMerged: false,
          threadSize: 1,
          originalText: '@myAlphaDrops @Bybit_Official @use_corn 8 billion',
          thread: [],
          hashtags: [],
          mentions: [
            { username: 'myAlphaDrops', id: '' },
            { username: 'Bybit_Official', id: '' },
            { username: 'use_corn', id: '' },
          ],
          urls: [],
          likes: 0,
          retweets: 0,
          replies: 0,
          views: 0,
          bookmarkCount: 0,
          photos: [],
          videos: [],
          homeTimeline: {
            publicMetrics: {
              likes: 0,
              retweets: 0,
              replies: 0,
            },
            entities: {
              hashtags: [],
              mentions: [
                { username: 'myAlphaDrops', id: '' },
                { username: 'Bybit_Official', id: '' },
                { username: 'use_corn', id: '' },
              ],
              urls: [],
            },
          },
        },
        {
          id: '80f56656-7091-47d7-b742-222faacc04d4',
          tweet_id: '1904907929670869288',
          text: '@Bybit_Official @use_corn So, $CORN TGE in 2 days\n\nHow many points do you have?',
          username: 'myAlphaDrops',
          status: 'pending',
          createdAt: new Date('2025-04-08T05:34:41.039Z'),
          isThreadMerged: false,
          threadSize: 1,
          originalText:
            '@Bybit_Official @use_corn So, $CORN TGE in 2 days\n\nHow many points do you have?',
          thread: [],
          hashtags: [],
          mentions: [
            { username: 'Bybit_Official', id: '' },
            { username: 'use_corn', id: '' },
          ],
          urls: [],
          likes: 0,
          retweets: 0,
          replies: 0,
          views: 0,
          bookmarkCount: 0,
          photos: [],
          videos: [],
          homeTimeline: {
            publicMetrics: {
              likes: 0,
              retweets: 0,
              replies: 0,
            },
            entities: {
              hashtags: [],
              mentions: [
                { username: 'Bybit_Official', id: '' },
                { username: 'use_corn', id: '' },
              ],
              urls: [],
            },
          },
        },
        {
          id: '97724a0e-14ba-459f-8bf3-8f92e680111e',
          tweet_id: '1904896123216502938',
          text: '📣 $CORN is coming soon to the #BybitSpot trading platform with @use_corn!\n\nListing time: Mar 28th, 10AM UTC. Stay tuned for more!\n\n#BybitListing #TheCryptoArk https://t.co/Q7a9IUsn21',
          username: 'Bybit_Official',
          status: 'pending',
          createdAt: new Date('2025-04-08T05:34:41.039Z'),
          isThreadMerged: false,
          threadSize: 1,
          originalText:
            '📣 $CORN is coming soon to the #BybitSpot trading platform with @use_corn!\n\nListing time: Mar 28th, 10AM UTC. Stay tuned for more!\n\n#BybitListing #TheCryptoArk https://t.co/Q7a9IUsn21',
          thread: [],
          hashtags: ['BybitSpot', 'BybitListing', 'TheCryptoArk'],
          mentions: [{ username: 'use_corn', id: '' }],
          urls: ['https://t.co/Q7a9IUsn21'],
          likes: 0,
          retweets: 0,
          replies: 0,
          views: 0,
          bookmarkCount: 0,
          photos: [],
          videos: [],
          homeTimeline: {
            publicMetrics: {
              likes: 0,
              retweets: 0,
              replies: 0,
            },
            entities: {
              hashtags: ['BybitSpot', 'BybitListing', 'TheCryptoArk'],
              mentions: [{ username: 'use_corn', id: '' }],
              urls: ['https://t.co/Q7a9IUsn21'],
            },
          },
        },
      ],
      quotedTweets: [],
      retweetedTweets: [],
    },
  },
];

// Combined mock tweets for testing
export const mockTweets: Tweet[] = [...mockCryptoTweets];
