export enum ServiceTypeExtension {
  CONFIG = 'token-monitor-config',
  TOKEN_MONITOR = 'TOKEN_MONITOR',
  BUNDLE_ANALYSIS = 'BUNDLE_ANALYSIS',
  TRANSACTION = 'TRANSACTION',
  HELIUS_TRANSACTION = 'HELIUS_TRANSACTION',
}
