name: CI Quality Checks

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

# Add explicit permissions for the workflow
permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run linting on all packages
        run: bun run lint

      - name: Check formatting on all packages
        run: bun run format

      - name: Run tests (if any)
        run: |
          if [ -f "backend/package.json" ] && grep -q '"test"' backend/package.json; then
            echo "Running backend tests..."
            bun run --cwd backend test || echo "Backend tests failed or not configured"
          fi
          if [ -f "shared/package.json" ] && grep -q '"test"' shared/package.json; then
            echo "Running shared tests..."
            bun run --cwd shared test || echo "Shared tests failed or not configured"
          fi
        continue-on-error: true