name: Docker Build and Push

on:
  push:
    branches:
      - main
      - dev
    # Only trigger if Dockerfile or backend files change
    paths:
      - 'Dockerfile'
      - 'backend/**'
      - '.github/workflows/docker-publish.yml' # Also trigger if the workflow itself changes

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Needed to push to Docker Hub (or GHCR)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine Image Tag
        id: docker_meta
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "TAG=latest" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "TAG=dev" >> $GITHUB_OUTPUT
          else
            # Handle other branches or tags if necessary, e.g., use commit SHA
            echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          fi
          echo "REPO=${{ secrets.DOCKERHUB_USERNAME }}/bork-tools" >> $GITHUB_OUTPUT # Replace bork-tools if needed

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.docker_meta.outputs.REPO }}:${{ steps.docker_meta.outputs.TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max 